\set ON_ERROR_STOP on

create table if not exists sales_person (
  id             bigint primary key generated by default as identity,
  created_at     timestamp default now(),
  code           text unique not null,
  name           text not null,
  start_work_date date
);

alter table invoice
  add column if not exists sales_person_id bigint references sales_person(id)
    on delete set null
    on update cascade;

INSERT INTO sales_person (id, created_at, code, name, start_work_date) VALUES (1,  '2026-01-01 00:00:00+00', 'SP001', 'Somchai Jaidee',     '2020-03-01') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date) VALUES (2,  '2026-01-01 00:00:00+00', 'SP002', 'Nattaporn Srisuk',   '2019-07-15') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date) VALUES (3,  '2026-01-01 00:00:00+00', 'SP003', 'Apinya Wongsiri',    '2021-01-10') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date) VALUES (4,  '2026-01-01 00:00:00+00', 'SP004', 'Chaiwat Meechai',    '2018-05-20') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date) VALUES (5,  '2026-01-01 00:00:00+00', 'SP005', 'Pornpan Rattana',    '2022-09-01') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date) VALUES (6,  '2026-01-01 00:00:00+00', 'SP006', 'Wanchai Thammasat',  '2017-11-30') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date) VALUES (7,  '2026-01-01 00:00:00+00', 'SP007', 'Sukanya Prempree',   '2023-02-14') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date) VALUES (8,  '2026-01-01 00:00:00+00', 'SP008', 'Piyawat Khumdee',    '2020-08-08') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date) VALUES (9,  '2026-01-01 00:00:00+00', 'SP009', 'Malee Somboon',      '2016-04-22') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date) VALUES (10, '2026-01-01 00:00:00+00', 'SP010', 'Teerawat Phoomchai', '2024-01-05') ON CONFLICT DO NOTHING;

SELECT setval(pg_get_serial_sequence('sales_person', 'id'), coalesce(max(id), 0) + 1, false) FROM sales_person;
