ALTER TABLE invoice_line_item
  ADD COLUMN IF NOT EXISTS line_discount_percent numeric(5,2)  NOT NULL DEFAULT 0.00,
  -- ^ line_discount_percent: 0.00 – 100.00
  ADD COLUMN IF NOT EXISTS line_discount_amount  numeric(14,2) NOT NULL DEFAULT 0.00,
  -- ^ line_discount_amount: extended_price * percent / 100
  ADD COLUMN IF NOT EXISTS line_net_price  numeric(14,2) NOT NULL DEFAULT 0.00;
  -- ^ line_net_price: extended_price - discount_amount

-- Backfill existing rows (discount was 0, so net = extended)
UPDATE invoice_line_item
  SET line_net_price = extended_price   -- line_net_price
  WHERE line_discount_amount = 0 AND extended_price IS NOT NULL;   -- line_discount_amount

ALTER TABLE invoice
  ADD COLUMN IF NOT EXISTS vat_rate  numeric(5,4)  NOT NULL DEFAULT 0.07,
  -- ^ vat_rate: stored as decimal (0.07 = 7%)
  ADD COLUMN IF NOT EXISTS total_price  numeric(14,2),
  -- ^ total_price: SUM(extended_price)
  ADD COLUMN IF NOT EXISTS total_discount  numeric(14,2) NOT NULL DEFAULT 0.00,
  -- ^ total_discount: SUM(line_discount_amount)
  ADD COLUMN IF NOT EXISTS vat_amount  numeric(14,2);
  -- ^ vat_amount: (total_price - total_discount) * vat_rate

UPDATE invoice SET total_price = total_amount  WHERE total_price IS NULL;   -- total_price, total_price
UPDATE invoice SET vat_amount = vat           WHERE vat_amount IS NULL;   -- vat_amount, vat_amount

CREATE TABLE IF NOT EXISTS configuration (   -- configuration
  id     bigint primary key generated by default as identity,
  key    text unique not null,
  value  text not null
);

INSERT INTO configuration (key, value)
  VALUES ('vat_percent', '7') 
  ON CONFLICT DO NOTHING;

SELECT setval(pg_get_serial_sequence('configuration', 'id'), coalesce(max(id), 0) + 1, false)
  FROM configuration;
