create table if not exists sales_person(
    spID bigint primary key generated by default as identity,
    code varchar(10) unique not null,
    spName varchar(100),
    start_work_date date not null
);

INSERT INTO sales_person (code, spName, start_work_date) VALUES
('SP001', 'Alice Thompson', '2020-03-15'),
('SP002', 'Bob Richards', '2021-06-01'),
('SP003', 'Charlie Davis', '2019-11-20'),
('SP004', 'Diana Prince', '2022-01-10'),
('SP005', 'Edward Norton', '2018-05-22'),
('SP006', 'Fiona Gallagher', '2023-02-14'),
('SP007', 'George Miller', '2021-09-30'),
('SP008', 'Hannah Abbott', '2020-12-05'),
('SP009', 'Ian Wright', '2017-08-12'),
('SP010', 'Julia Roberts', '2022-11-11');