create table if not exists sales_person (
  id             bigint primary key generated by default as identity,
  created_at     timestamp default now(),
  code           text unique not null,
  name           text not null,
  start_work_date date
);

alter table invoice
  add column if not exists sales_person_id bigint references sales_person(id)
    on delete set null
    on update cascade;

INSERT INTO sales_person (id, created_at, code, name, start_work_date) VALUES (1,  '2026-01-01 00:00:00+00', 'SP001', 'Somchai Jaidee',     '2020-03-01') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date) VALUES (2,  '2026-01-01 00:00:00+00', 'SP002', 'Nattaporn Srisuk',   '2019-07-15') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date) VALUES (3,  '2026-01-01 00:00:00+00', 'SP003', 'Apinya Wongsiri',    '2021-01-10') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date) VALUES (4,  '2026-01-01 00:00:00+00', 'SP004', 'Chaiwat Meechai',    '2018-05-20') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date) VALUES (5,  '2026-01-01 00:00:00+00', 'SP005', 'Pornpan Rattana',    '2022-09-01') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date) VALUES (6,  '2026-01-01 00:00:00+00', 'SP006', 'Wanchai Thammasat',  '2017-11-30') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date) VALUES (7,  '2026-01-01 00:00:00+00', 'SP007', 'Sukanya Prempree',   '2023-02-14') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date) VALUES (8,  '2026-01-01 00:00:00+00', 'SP008', 'Piyawat Khumdee',    '2020-08-08') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date) VALUES (9,  '2026-01-01 00:00:00+00', 'SP009', 'Malee Somboon',      '2016-04-22') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date) VALUES (10, '2026-01-01 00:00:00+00', 'SP010', 'Teerawat Phoomchai', '2024-01-05') ON CONFLICT DO NOTHING;


CREATE TABLE IF NOT EXISTS configuration (
  id     bigint primary key generated by default as identity,
  key    text unique not null,
  value  text not null
);

INSERT INTO configuration (key, value)
  VALUES ('vat_percent', '7') 
  ON CONFLICT DO NOTHING;

ALTER TABLE invoice_line_item
  ADD COLUMN IF NOT EXISTS line_discount_percent numeric(5,2)  NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS line_discount_amount  numeric(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS line_net_price  numeric(14,2) NOT NULL DEFAULT 0.00;

UPDATE invoice_line_item
  SET line_net_price = extended_price
  WHERE line_discount_amount = 0 AND extended_price IS NOT NULL;

ALTER TABLE invoice
  ADD COLUMN IF NOT EXISTS vat_rate  numeric(5,4)  NOT NULL DEFAULT 0.07,
  ADD COLUMN IF NOT EXISTS total_price  numeric(14,2),
  ADD COLUMN IF NOT EXISTS total_discount  numeric(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS vat_amount  numeric(14,2);

UPDATE invoice SET total_price = total_amount  WHERE total_price IS NULL;
UPDATE invoice SET vat_amount = vat           WHERE vat_amount IS NULL;

